//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class edurp_devEntities : DbContext
    {
        public edurp_devEntities()
            : base("name=edurp_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChapterMaster> ChapterMasters { get; set; }
        public virtual DbSet<CourseMaster> CourseMasters { get; set; }
        public virtual DbSet<CourseSubjectAssociation> CourseSubjectAssociations { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<ProgramStudy> ProgramStudies { get; set; }
        public virtual DbSet<ProgramStudyCourseAssociation> ProgramStudyCourseAssociations { get; set; }
        public virtual DbSet<ProgramStudyFeeAssociation> ProgramStudyFeeAssociations { get; set; }
        public virtual DbSet<SubjectChapterAssociation> SubjectChapterAssociations { get; set; }
        public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }
    
        public virtual ObjectResult<GetProgramStudyCourseList_Result> GetProgramStudyCourseList(Nullable<int> universityid, Nullable<int> programstudyid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyCourseList_Result>("GetProgramStudyCourseList", universityidParameter, programstudyidParameter);
        }
    
        public virtual ObjectResult<GetProgramStudyCourseNotLinkedList_Result> GetProgramStudyCourseNotLinkedList(Nullable<int> universityid, Nullable<int> programstudyid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyCourseNotLinkedList_Result>("GetProgramStudyCourseNotLinkedList", universityidParameter, programstudyidParameter);
        }
    
        public virtual ObjectResult<GetProgramStudyDetail_Result> GetProgramStudyDetail(Nullable<int> universityid, Nullable<int> programstudyid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyDetail_Result>("GetProgramStudyDetail", universityidParameter, programstudyidParameter);
        }
    
        public virtual ObjectResult<GetProgramStudyFeesList_Result> GetProgramStudyFeesList(Nullable<int> universityid, Nullable<int> programstudyid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyFeesList_Result>("GetProgramStudyFeesList", universityidParameter, programstudyidParameter);
        }
    
        public virtual ObjectResult<GetProgramStudyFeesNotLinkedList_Result> GetProgramStudyFeesNotLinkedList(Nullable<int> universityid, Nullable<int> programstudyid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyFeesNotLinkedList_Result>("GetProgramStudyFeesNotLinkedList", universityidParameter, programstudyidParameter);
        }
    
        public virtual ObjectResult<GetProgramStudyID_Result> GetProgramStudyID(Nullable<int> universityid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramStudyID_Result>("GetProgramStudyID", universityidParameter);
        }
    
        public virtual ObjectResult<GetSubjectDetail_Result> GetSubjectDetail(Nullable<int> universityid, Nullable<int> subjectid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var subjectidParameter = subjectid.HasValue ?
                new ObjectParameter("subjectid", subjectid) :
                new ObjectParameter("subjectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectDetail_Result>("GetSubjectDetail", universityidParameter, subjectidParameter);
        }
    
        public virtual ObjectResult<GetSubjectList_Result> GetSubjectList(Nullable<int> universityid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectList_Result>("GetSubjectList", universityidParameter);
        }
    
        public virtual int LinkProgramStudyCourse(Nullable<int> universityid, Nullable<int> programstudyid, Nullable<int> courseid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LinkProgramStudyCourse", universityidParameter, programstudyidParameter, courseidParameter);
        }
    
        public virtual int LinkProgramStudyFees(Nullable<int> universityid, Nullable<int> programstudyid, Nullable<int> feeid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            var feeidParameter = feeid.HasValue ?
                new ObjectParameter("feeid", feeid) :
                new ObjectParameter("feeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LinkProgramStudyFees", universityidParameter, programstudyidParameter, feeidParameter);
        }
    
        public virtual int RemoveSubject(Nullable<int> universityid, Nullable<int> subjectid, Nullable<int> updatedby)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var subjectidParameter = subjectid.HasValue ?
                new ObjectParameter("subjectid", subjectid) :
                new ObjectParameter("subjectid", typeof(int));
    
            var updatedbyParameter = updatedby.HasValue ?
                new ObjectParameter("updatedby", updatedby) :
                new ObjectParameter("updatedby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveSubject", universityidParameter, subjectidParameter, updatedbyParameter);
        }
    
        public virtual int UnLinkProgramStudyCourse(Nullable<int> universityid, Nullable<int> programstudyid, Nullable<int> courseid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UnLinkProgramStudyCourse", universityidParameter, programstudyidParameter, courseidParameter);
        }
    
        public virtual int UnLinkProgramStudyFees(Nullable<int> universityid, Nullable<int> programstudyid, Nullable<int> feeid)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var programstudyidParameter = programstudyid.HasValue ?
                new ObjectParameter("programstudyid", programstudyid) :
                new ObjectParameter("programstudyid", typeof(int));
    
            var feeidParameter = feeid.HasValue ?
                new ObjectParameter("feeid", feeid) :
                new ObjectParameter("feeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UnLinkProgramStudyFees", universityidParameter, programstudyidParameter, feeidParameter);
        }
    
        public virtual int UpdateSubject(Nullable<int> universityid, Nullable<int> subjectid, string subjectcode, string subjectname, Nullable<int> sks, Nullable<int> updatedby)
        {
            var universityidParameter = universityid.HasValue ?
                new ObjectParameter("universityid", universityid) :
                new ObjectParameter("universityid", typeof(int));
    
            var subjectidParameter = subjectid.HasValue ?
                new ObjectParameter("subjectid", subjectid) :
                new ObjectParameter("subjectid", typeof(int));
    
            var subjectcodeParameter = subjectcode != null ?
                new ObjectParameter("subjectcode", subjectcode) :
                new ObjectParameter("subjectcode", typeof(string));
    
            var subjectnameParameter = subjectname != null ?
                new ObjectParameter("subjectname", subjectname) :
                new ObjectParameter("subjectname", typeof(string));
    
            var sksParameter = sks.HasValue ?
                new ObjectParameter("sks", sks) :
                new ObjectParameter("sks", typeof(int));
    
            var updatedbyParameter = updatedby.HasValue ?
                new ObjectParameter("updatedby", updatedby) :
                new ObjectParameter("updatedby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSubject", universityidParameter, subjectidParameter, subjectcodeParameter, subjectnameParameter, sksParameter, updatedbyParameter);
        }
    }
}
